  const Cinsiyet = [
    { key: 'Kadın', value: 'Kadın', text: 'Kadın' },
    { key: 'Erkek', value: 'Erkek', text: 'Erkek' },
  ]
  const MedeniDurum = [
    { key: 'Bekar', value: 'Bekar', text: 'Bekar' },
    { key: 'Evli', value: 'Evli', text: 'Evli' },
  ]
  const AskelikDurumu = [
    { key: 'Tamamlandı', value: 'Tamamlandı', text: 'Tamamlandı' },
    { key: 'Tecilli', value: 'Tecilli', text: 'Tecilli' },
    { key: 'Muaf', value: 'Muaf', text: 'Muaf' },
  ]
  const Durum = [
    { key: 'Evet', value: 'Evet', text: 'Evet' },
    { key: 'Hayır', value: 'Hayır', text: 'Hayır' },
  ]
  const BasPozisyon = [
    { key: 'GB', value: 'Genel Başvuru', text: 'Genel Başvuru' },
    { key: 'YGU', value: 'Yazılım Uzmanı', text: 'Yazılım Uzmanı' },
  ]
  const Days = [
    { key: '1', value: '1', text: '1' },
    { key: '2', value: '2', text: '2' },
    { key: '3', value: '3', text: '3' },
    { key: '4', value: '4', text: '4' },
    { key: '5', value: '5', text: '5' },
    { key: '6', value: '6', text: '6' },
    { key: '7', value: '7', text: '7' },
    { key: '8', value: '8', text: '8' },
    { key: '9', value: '9', text: '9' },
    { key: '10', value: '10', text: '10' },
    { key: '11', value: '11', text: '11' },
    { key: '12', value: '12', text: '12' },
    { key: '13', value: '13', text: '13' },
    { key: '14', value: '14', text: '14' },
    { key: '15', value: '15', text: '15' },
    { key: '16', value: '16', text: '16' },
    { key: '17', value: '17', text: '17' },
    { key: '18', value: '18', text: '18' },
    { key: '19', value: '19', text: '19' },
    { key: '20', value: '20', text: '20' },
    { key: '21', value: '21', text: '21' },
    { key: '22', value: '22', text: '22' },
    { key: '23', value: '23', text: '23' },
    { key: '24', value: '24', text: '24' },
    { key: '25', value: '25', text: '25' },
    { key: '26', value: '26', text: '26' },
    { key: '27', value: '27', text: '27' },
    { key: '28', value: '28', text: '28' },
    { key: '29', value: '29', text: '29' },
    { key: '30', value: '30', text: '30' },
    { key: '31', value: '31', text: '31' },
  ]
  const Months = [
    { key: 'Ocak', value: '01', text: '01' },
    { key: 'Şubat', value: '02', text: '02' },
    { key: 'Mart', value: '03', text: '03' },
    { key: 'Nisan', value: '04', text: '04' },
    { key: 'Mayıs', value: '05', text: '05' },
    { key: 'Haziran', value: '06', text: '06' },
    { key: 'Temmuz', value: '07', text: '07' },
    { key: 'Ağustos', value: '08', text: '08' },
    { key: 'Eylül', value: '09', text: '09' },
    { key: 'Ekim', value: '10', text: '10' },
    { key: 'Kasım', value: '11', text: '11' },
    { key: 'Aralık', value: '12', text: '12' },
  ]
  const Years = [
    { key: '2022', value: '2022', text: '2022' },
    { key: '2021', value: '2021', text: '2021' },
    { key: '2020', value: '2020', text: '2020' },
    { key: '2019', value: '2019', text: '2019' },
    { key: '2018', value: '2018', text: '2018' },
    { key: '2017', value: '2017', text: '2017' },
    { key: '2016', value: '2016', text: '2016' },
    { key: '2015', value: '2015', text: '2015' },
    { key: '2014', value: '2014', text: '2014' },
    { key: '2013', value: '2013', text: '2013' },
    { key: '2012', value: '2012', text: '2012' },
    { key: '2011', value: '2011', text: '2011' },
    { key: '2010', value: '2010', text: '2010' },
    { key: '2009', value: '2009', text: '2009' },
    { key: '2008', value: '2008', text: '2008' },
    { key: '2007', value: '2007', text: '2007' },
    { key: '2006', value: '2006', text: '2006' },
    { key: '2005', value: '2005', text: '2005' },
    { key: '2004', value: '2004', text: '2004' },
    { key: '2003', value: '2003', text: '2003' },
    { key: '2002', value: '2002', text: '2002' },
    { key: '2001', value: '2001', text: '2001' },
    { key: '2000', value: '2000', text: '2000' },
    { key: '1999', value: '1999', text: '1999' },
    { key: '1998', value: '1998', text: '1998' },
    { key: '1997', value: '1997', text: '1997' },
    { key: '1996', value: '1996', text: '1996' },
    { key: '1995', value: '1995', text: '1995' },
    { key: '1994', value: '1994', text: '1994' },
    { key: '1993', value: '1993', text: '1993' },
    { key: '1992', value: '1992', text: '1992' },
    { key: '1991', value: '1991', text: '1991' },
    { key: '1990', value: '1990', text: '1990' },
    { key: '1989', value: '1989', text: '1989' },
    { key: '1988', value: '1988', text: '1988' },
    { key: '1987', value: '1987', text: '1987' },
    { key: '1986', value: '1986', text: '1986' },
    { key: '1985', value: '1985', text: '1985' },
    { key: '1984', value: '1984', text: '1984' },
    { key: '1983', value: '1983', text: '1983' },
    { key: '1982', value: '1982', text: '1982' },
    { key: '1981', value: '1981', text: '1981' },
    { key: '1980', value: '1980', text: '1980' },
    { key: '1979', value: '1979', text: '1979' },
    { key: '1978', value: '1978', text: '1978' },
    { key: '1977', value: '1977', text: '1977' },
    { key: '1976', value: '1976', text: '1976' },
    { key: '1975', value: '1975', text: '1975' },
    { key: '1974', value: '1974', text: '1974' },
    { key: '1973', value: '1973', text: '1973' },
    { key: '1972', value: '1972', text: '1972' },
    { key: '1971', value: '1971', text: '1971' },
    { key: '1970', value: '1970', text: '1970' },
    { key: '1969', value: '1969', text: '1969' },
    { key: '1968', value: '1968', text: '1968' },
    { key: '1967', value: '1967', text: '1967' },
    { key: '1966', value: '1966', text: '1966' },
    { key: '1965', value: '1965', text: '1965' },
    { key: '1964', value: '1964', text: '1964' },
    { key: '1963', value: '1963', text: '1963' },
    { key: '1962', value: '1962', text: '1962' },
    { key: '1961', value: '1961', text: '1961' },
    { key: '1960', value: '1960', text: '1960' },
    
  ]
  const Cities = [
    { key: 'İstanbul',  value: 'İstanbul' ,  text: 'İstanbul' },
    { key: 'Ankara', value: 'Ankara', text: 'Ankara' },
    { key: 'Adana', value: 'Adana', text: 'Adana' },
    { key: 'Adıyaman', value: 'Adıyaman', text: 'Adıyaman' },
    { key: 'Afyonkarahisar', value: 'Afyonkarahisar', text: 'Afyonkarahisar' },
    { key: 'Ağrı', value: 'Ağrı', text: 'Ağrı' },
    { key: 'Aksaray', value: 'Aksaray', text: 'Aksaray' },
    { key: 'Amasya', value: 'Amasya', text: 'Amasya' },
    { key: 'Antalya', value: 'Antalya', text: 'Antalya' },
    { key: 'Ardahan', value: 'Ardahan', text: 'Ardahan' },
    { key: 'Artvin', value: 'Artvin', text: 'Artvin' },
    { key: 'Aydın', value: 'Aydın', text: 'Aydın' },
    { key: 'Balıkesir', value: 'Balıkesir', text: 'Balıkesir' },
    { key: 'Bartın', value: 'Bartın', text: 'Bartın' },
    { key: 'Batman', value: 'Batman', text: 'Batman' },
    { key: 'Bayburt', value: 'Bayburt', text: 'Bayburt' },
    { key: 'Bilecik', value: 'Bilecik', text: 'Bilecik' },
    { key: 'Bingöl', value: 'Bingöl', text: 'Bingöl' },
    { key: 'Bitlis', value: 'Bitlis', text: 'Bitlis' },
    { key: 'Bolu', value: 'Bolu', text: 'Bolu' },
    { key: 'Burdur', value: 'Burdur', text: 'Burdur' },
    { key: 'Bursa', value: 'Bursa', text: 'Bursa' },
    { key: 'Çanakkale', value: 'Çanakkale', text: 'Çanakkale' },
    { key: 'Çankırı', value: 'Çankırı', text: 'Çankırı' },
    { key: 'Çorum', value: 'Çorum', text: 'Çorum' },
    { key: 'Denizli', value: 'Denizli', text: 'Denizli' },
    { key: 'Diyarbakır', value: 'Diyarbakır', text: 'Diyarbakır' },
    { key: 'Düzce', value: 'Düzce', text: 'Düzce' },
    { key: 'Edirne', value: 'Edirne', text: 'Edirne' },
    { key: 'Elâzığ', value: 'Elâzığ', text: 'Elâzığ' },
    { key: 'Erzincan', value: 'Erzincan', text: 'Erzincan' },
    { key: 'Erzurum', value: 'Erzurum', text: 'Erzurum' },
    { key: 'Eskişehir', value: 'Eskişehir', text: 'Eskişehir' },
    { key: 'Gaziantep', value: 'Gaziantep', text: 'Gaziantep' },
    { key: 'Giresun', value: 'Giresun', text: 'Giresun' },
    { key: 'Gümüşhane', value: 'Gümüşhane', text: 'Gümüşhane' },
    { key: 'Hakkâri', value: 'Hakkâri', text: 'Hakkâri' },
    { key: 'Hatay', value: 'Hatay', text: 'Hatay' },
    { key: 'Iğdır', value: 'Iğdır', text: 'Iğdır' },
    { key: 'Isparta', value: 'Isparta', text: 'Isparta' },
    { key: 'İzmir', value: 'İzmir', text: 'İzmir' },
    { key: 'Kahramanmaraş', value: 'Kahramanmaraş', text: 'Kahramanmaraş' },
    { key: 'Karabük', value: 'Karabük', text: 'Karabük' },
    { key: 'Karaman', value: 'Karaman', text: 'Karaman' },
    { key: 'Kars', value: 'Kars', text: 'Kars' },
    { key: 'Kastamonu', value: 'Kastamonu', text: 'Kastamonu' },
    { key: 'Kayseri', value: 'Kayseri', text: 'Kayseri' },
    { key: 'Kırıkkale', value: 'Kırıkkale', text: 'Kırıkkale' },
    { key: 'Kırklareli', value: 'Kırklareli', text: 'Kırklareli' },
    { key: 'Kırşehir', value: 'Kırşehir', text: 'Kırşehir' },
    { key: 'Kilis', value: 'Kilis', text: 'Kilis' },
    { key: 'Kocaeli', value: 'Kocaeli', text: 'Kocaeli' },
    { key: 'Konya', value: 'Konya', text: 'Konya' },
    { key: 'Kütahya', value: 'Kütahya', text: 'Kütahya' },
    { key: 'Malatya', value: 'Malatya', text: 'Malatya' },
    { key: 'Manisa', value: 'Manisa', text: 'Manisa' },
    { key: 'Mardin', value: 'Mardin', text: 'Mardin' },
    { key: 'Mersin', value: 'Mersin', text: 'Mersin' },
    { key: 'Muğla', value: 'Muğla', text: 'Muğla' },
    { key: 'Muş', value: 'Muş', text: 'Muş' },
    { key: 'Nevşehir', value: 'Nevşehir', text: 'Nevşehir' },
    { key: 'Niğde', value: 'Niğde', text: 'Niğde' },
    { key: 'Ordu', value: 'Ordu', text: 'Ordu' },
    { key: 'Osmaniye', value: 'Osmaniye', text: 'Osmaniye' },
    { key: 'Rize', value: 'Rize', text: 'Rize' },
    { key: 'Sakarya', value: 'Sakarya', text: 'Sakarya' },
    { key: 'Samsun', value: 'Samsun', text: 'Samsun' },
    { key: 'Siirt', value: 'Siirt', text: 'Siirt' },
    { key: 'Sinop', value: 'Sinop', text: 'Sinop' },
    { key: 'Sivas', value: 'Sivas', text: 'Sivas' },
    { key: 'Şanlıurfa', value: 'Şanlıurfa', text: 'Şanlıurfa' },
    { key: 'Şırnak', value: 'Şırnak', text: 'Şırnak' },
    { key: 'Tekirdağ', value: 'Tekirdağ', text: 'Tekirdağ' },
    { key: 'Tokat', value: 'Tokat', text: 'Tokat' },
    { key: 'Trabzon', value: 'Trabzon', text: 'Trabzon' },
    { key: 'Tunceli', value: 'Tunceli', text: 'Tunceli' },
    { key: 'Uşak', value: 'Uşak', text: 'Uşak' },
    { key: 'Van', value: 'Van', text: 'Van' },
    { key: 'Yalova', value: 'Yalova', text: 'Yalova' },
    { key: 'Yozgat', value: 'Yozgat', text: 'Yozgat' },
    { key: 'Zonguldak', value: 'Zonguldak', text: 'Zonguldak' },
  ]
  const Status = [
    { key: 'Hemen',  value: 'Hemen' ,  text: 'Hemen' },
    { key: 'İhbar Sürem Bittiğinde', value: 'İhbar Sürem Bittiğinde', text: 'İhbar Sürem Bittiğinde' },
    { key: '1 Ay Sonra', value: '1 Ay Sonra', text: '1 Ay Sonra' },
    { key: '2 Ay Sonra', value: '2 Ay Sonra', text: '2 Ay Sonra' },
  ]
  const Value = [
    { key: 'Belirtmek İstemiyorum',  value: 'Belirtmek İstemiyorum' ,  text: 'Belirtmek İstemiyorum' },
    { key: '2000-3000',  value: '2000-3000' ,  text: '2000-3000' },
    { key: '3000-4000',  value: '3000-4000' ,  text: '3000-4000' },
    { key: '4000-5000',  value: '4000-5000' ,  text: '4000-5000' },
    { key: '5000-6000',  value: '5000-6000' ,  text: '5000-6000' },
    { key: '6000-7000',  value: '6000-7000' ,  text: '6000-7000' },
    { key: '7000-8000',  value: '7000-8000' ,  text: '7000-8000' },
    { key: '8000-9000',  value: '8000-9000' ,  text: '8000-9000' },
    { key: '10000 ve üzeri',  value: '10000 ve üzeri' ,  text: '10000 ve üzeri' },
  ]
  const EgitimDurumu = [
    { key: 'Yüksek Lisans - Mezun',  value: 'Yüksek Lisans - Mezun' ,  text: 'Yüksek Lisans - Mezun' },
    { key: 'Yüksek Lisans - Öğrenci',  value: 'Yüksek Lisans - Öğrenci' ,  text: 'Yüksek Lisans - Öğrenci' },
    { key: 'Lisans - Öğrenci',  value: 'Lisans - Öğrenci' ,  text: 'Lisans - Öğrenci' },
    { key: 'Lisans - Mezun',  value: 'Lisans - Mezun' ,  text: 'Lisans - Mezun' },
    { key: 'Ön Lisans - Öğrenci',  value: 'Ön Lisans - Öğrenci' ,  text: 'Ön Lisans - Öğrenci' },
    { key: 'Ön Lisans - Mezun',  value: 'Ön Lisans - Mezun' ,  text: 'Ön Lisans - Mezun' },
    { key: 'Lise - Öğrenci', value: 'Lise - Öğrenci', text: 'Lise - Öğrenci' },
    { key: 'Lise - Mezun', value: 'Lise - Mezun', text: 'Lise - Mezun' },
    { key: 'İlkokul', value: 'İlkokul', text: 'İlkokul' },
  ]

export {Cinsiyet, MedeniDurum, AskelikDurumu, Durum, BasPozisyon, Days, Months, Years, Cities, Status, Value, EgitimDurumu};